### ISSUE TITLE
FontiGrid Icon

### ISSUE THREAD

**Issue by BryMD** [pthalin/bittboy-j2me#3]
Totally LOVE your project! Whipped up a quick FontiGrid compliant icon for myself. Grab it for yourself if you're interested.

![j2me](https://user-images.githubusercontent.com/65721499/90816408-7dfcb100-e32c-11ea-9159-71e33b857c3d.png)

On a side note, do you know if bittboy-j2me prefers any particular flavor of .jars (ie. Nokia, Sony Ericsson, Samsung, Siemens etc.)?

Keep up the good work!

**Comment by pthalin** [comment]
Thanks! I had most luck with Nokia or Sony Ericsson. I haven't optimized it for any specific phone.
