### ISSUE TITLE
Hope to display in-game text

### ISSUE THREAD

**Issue by ZOMBIE39** [pthalin/bittboy-j2me#4]
I used a translation site because my English is not good. 
The java emulator came up and made me dig out miyoo to play with it again.After trying out many games, I found that some of the text within the game would not be displayed. Because there is no way to find java games in English, and I think you should have tested it, so I guess it is possible that the Chinese language library is missing. Of course, after all, I don't know much about this and can only guess. If you can, I hope you can solve this problem.It has been a long time wish to have a small device with buttons to play the previous java games.
I would like to thank you very much for your hard work and dedication so that this little machine can be rejuvenated.
![QQ图片20210407104906](https://user-images.githubusercontent.com/37724369/113798984-2f9f0400-978f-11eb-9559-2ea177de44c4.jpg)
![QQ图片20210407105025](https://user-images.githubusercontent.com/37724369/113799212-9e7c5d00-978f-11eb-8c94-8b34f0ad186b.jpg)
![QQ图片20210407105028](https://user-images.githubusercontent.com/37724369/113799214-a0deb700-978f-11eb-92c5-c483f905ec0e.jpg)

**Comment by pthalin** [comment]
Thanks for your report. Unfortunately I have no plans to do any development any time soon on this project. Let hope someone else is up for a challenge :-)
