### ISSUE TITLE
Setup J2me in SimpleMenu

### ISSUE THREAD

**Issue by Grayjks** [pthalin/bittboy-j2me#7]
Hello, i have a question, How i can setup J2me to work in simple menu. i use Powkiddy V90 and i already create selection of j2me but the problem is i don't know where the execs of J2me to set to work. can anyone help me find execs of j2me ?
My code in selecion is : 
[J2ME]
execs = ?
romDirs = /mnt/roms/J2ME/
romExts = .jar,.jad
but i can't find execs file to work

**Comment by pthalin** [comment]
This should work. 
https://raw.githubusercontent.com/pthalin/bittboy-j2me/master/bittboy-j2me

**Comment by Grayjks** [comment]
> This should work. https://raw.githubusercontent.com/pthalin/bittboy-j2me/master/bittboy-j2me

still not work bro, i try to open the game but that crash.

**Comment by Grayjks** [comment]
I just make that working by change the code to right type to simplemenu, that work, thank you for help <3 
and the code is
[J2ME]
execs = /mnt/emus/bittboy-j2me/bin/runjar.sh
romDirs = /mnt/roms/J2ME/
romExts = .jar,.jad
clock=702

> This should work. https://raw.githubusercontent.com/pthalin/bittboy-j2me/master/bittboy-j2me

**Comment by pthalin** [comment]
Unfortunately it doesn't work with all games. Try some different jar files. Make sure it is 176x220 resolution.
